config/routes.rb
Ecm::OpeningTimes::Backend::Engine.routes.draw do
  resources :branches do
    post :reposition, on: :member
  end
  resources :entries

  root to: 'home#index'
end

app/controllers/ecm/opening_times/backend/branches_controller.rb
module Ecm
  module OpeningTimes
    module Backend
      class BranchesController < Itsf::Backend::Resource::BaseController
        include ResourcesController::ActsAsListConcern

        helper Ecm::OpeningTimes::ApplicationHelper

        def self.resource_class
          Ecm::OpeningTimes::Branch
        end

        private

        def permitted_params
          params.require(:branch).permit(:name, :identifier)
        end
      end
    end
  end
end

app/controllers/ecm/opening_times/backend/entries_controller.rb
module Ecm
  module OpeningTimes
    module Backend
      class EntriesController < Itsf::Backend::Resource::BaseController
        def self.resource_class
          Ecm::OpeningTimes::Entry
        end

        private

        def permitted_params
          params.require(:entry).permit(:branch_id, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :open_all_day, :open_at, :close_at)
        end
      end
    end
  end
end

app/controllers/ecm/opening_times/backend/home_controller.rb
module Ecm
  module OpeningTimes
    module Backend
      class HomeController < Itsf::Backend::HomeController
      end
    end
  end
end

app/helpers/ecm/opening_times/backend/application_helper.rb
module Ecm
  module OpeningTimes
    module Backend
      module ApplicationHelper
      end
    end
  end
end

app/views/ecm/opening_times/backend/branches/_entries_form.haml
= form.input :monday
= form.input :tuesday
= form.input :wednesday
= form.input :thursday
= form.input :friday
= form.input :saturday
= form.input :sunday

= form.input :open_at, as: :string
= form.input :close_at, as: :string

= form.input :open_all_day

app/views/ecm/opening_times/backend/branches/_form.haml
= form.input :name
= form.input :identifier

app/views/ecm/opening_times/backend/branches/_show_extras.haml
.row
  .col-lg-12
    = render_collection(@resource.entries, Ecm::OpeningTimes::Entry, as: :bootstrap_table) do |table|
      = table.column :monday do |resource|
        - if resource.monday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :tuesday do |resource|
        - if resource.tuesday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :wednesday do |resource|
        - if resource.wednesday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :thursday do |resource|
        - if resource.thursday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :friday do |resource|
        - if resource.friday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :saturday do |resource|
        - if resource.saturday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :sunday do |resource|
        - if resource.sunday
          %div.text-center
            %i.glyphicon.glyphicon-ok
      = table.column :open_at
      = table.column :close_at
      = table.timestamps

app/views/ecm/opening_times/backend/branches/_table.haml
= table.acts_as_list_actions
= table.column :name
= table.column :identifier
= table.timestamps

app/views/ecm/opening_times/backend/entries/_form.haml
= form.association :branch

.well
  = form.input :monday
  = form.input :tuesday
  = form.input :wednesday
  = form.input :thursday
  = form.input :friday
  = form.input :saturday
  = form.input :sunday

.well
  #open-all-day.row
    .col-lg-12
      = form.input :open_all_day, as: :boolean, input_html: { data: { disables: '#opening-times input' } }

  .horizontal-separator= t('or')
  
  #opening-times.row
    .col-lg-6
      = form.input :open_at, as: :string, input_html: { value: form.object.open_at }
    .col-lg-6
      = form.input :close_at, as: :string, input_html: { value: form.object.close_at }

app/views/ecm/opening_times/backend/entries/_table.haml
= table.association :branch, label_method: :name, url: ->(entry) { branch_path(entry.branch) }
= table.column :monday do |resource|
  - if resource.monday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :tuesday do |resource|
  - if resource.tuesday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :wednesday do |resource|
  - if resource.wednesday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :thursday do |resource|
  - if resource.thursday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :friday do |resource|
  - if resource.friday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :saturday do |resource|
  - if resource.saturday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :sunday do |resource|
  - if resource.sunday
    - capture_haml do
      %div.text-center
        %i.glyphicon.glyphicon-ok
= table.column :open_at
= table.column :close_at
= table.timestamps

app/views/layouts/ecm/opening_times/backend/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opening Times</title>
  <%= stylesheet_link_tag    "ecm/opening_times/backend/application", media: "all" %>
  <%= javascript_include_tag "ecm/opening_times/backend/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>